### ISSUE TITLE
Mouse cursor

### ISSUE THREAD

**Issue by EdsonLuiz** [badruzeus/Hackintosh-Asus-A43SJ#2]
Normally, when you point your mouse over a link, it changes into a hand, if you want to resize a window, the cursor changes into a double arrow, and so forth, but  the mouse cursor doesn't change back to normal.  
How did you solve this problem?

**Comment by Wnine16** [comment]
sometimes i had the same issue too
but it will back to normal after a while

**Comment by EdsonLuiz** [comment]
Solved adding NVDAResman.kext in S/L/E.
No more problems with mouse cursor form, size or positioning.

**Comment by Wnine16** [comment]
I replace the NVDAResman.kext, and it worked. the mouse pointer has become normal. but when I install the WebDriver, the mouse pointer issue is up again. I tested many times, if I choose the System's default graphics driver, the mouse pointer will be okay to use. but when I choose the Nvidia WebDriver, the mouse pointer will have the issue.
